"""add indexes to foreign key columns

Revision ID: e37edf3be46e
Revises: e37edf3be46d
Create Date: 2025-11-05 12:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37edf3be46e'
down_revision: Union[str, None] = 'e37edf3be46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_broadcast_id'), 'broadcast_logs', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_logs_user_id'), 'broadcast_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaign_users_campaign_id'), 'campaign_users', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_users_user_id'), 'campaign_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_discount_template_id'), 'campaigns', ['discount_template_id'], unique=False)
    op.create_index(op.f('ix_campaigns_segment_id'), 'campaigns', ['segment_id'], unique=False)
    op.create_index(op.f('ix_cashiers_approved_by_admin_id'), 'cashiers', ['approved_by_admin_id'], unique=False)
    op.create_index(op.f('ix_discount_usage_logs_cashier_id'), 'discount_usage_logs', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_discount_usage_logs_discount_id'), 'discount_usage_logs', ['discount_id'], unique=False)
    op.create_index(op.f('ix_discount_usage_logs_user_id'), 'discount_usage_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_discounts_template_id'), 'discounts', ['template_id'], unique=False)
    op.create_index(op.f('ix_discounts_user_id'), 'discounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_discounts_user_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_template_id'), table_name='discounts')
    op.drop_index(op.f('ix_discount_usage_logs_user_id'), table_name='discount_usage_logs')
    op.drop_index(op.f('ix_discount_usage_logs_discount_id'), table_name='discount_usage_logs')
    op.drop_index(op.f('ix_discount_usage_logs_cashier_id'), table_name='discount_usage_logs')
    op.drop_index(op.f('ix_cashiers_approved_by_admin_id'), table_name='cashiers')
    op.drop_index(op.f('ix_campaigns_segment_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_discount_template_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaign_users_user_id'), table_name='campaign_users')
    op.drop_index(op.f('ix_campaign_users_campaign_id'), table_name='campaign_users')
    op.drop_index(op.f('ix_broadcast_logs_user_id'), table_name='broadcast_logs')
    op.drop_index(op.f('ix_broadcast_logs_broadcast_id'), table_name='broadcast_logs')
    op.drop_index(op.f('ix_audit_logs_admin_.id'), table_name='audit_logs')
    # ### end Alembic commands ###
